name: sepia
channels:
  - defaults
dependencies:
  - jupyter=1.0.0
  - matplotlib=3.2.1
  - numpy=1.16.4
  - pip=20.1.1
  - pyparsing=2.4.7
  - python=3.7.0
  - scipy=1.2.1
  - seaborn=0.10.1
  - setuptools=47.3.1
  - statsmodels=0.11.1
  - tqdm=4.46.1
prefix: //anaconda3/envs/sepia

